"""
This type stub file was generated by pyright.
"""

from .version import __version__, __version_info__

__all__ = ['__version__', '__version_info__', 'load_order']
def load_order(): # -> list[str]:
    """
    Returns a list of the module and sub-module names for asn1crypto in
    dependency load order, for the sake of live reloading code

    :return:
        A list of unicode strings of module names, as they would appear in
        sys.modules, ordered by which module should be reloaded first
    """
    ...

