"""
This type stub file was generated by pyright.
"""

"""
Exports the following items:

 - unwrap()
 - APIException()
"""
class APIException(Exception):
    """
    An exception indicating an API has been removed from asn1crypto
    """
    ...


def unwrap(string, *params): # -> str:
    """
    Takes a multi-line string and does the following:

     - dedents
     - converts newlines with text before and after into a single line
     - strips leading and trailing whitespace

    :param string:
        The string to format

    :param *params:
        Params to interpolate into the string

    :return:
        The formatted string
    """
    ...

