"""
This type stub file was generated by pyright.
"""

import codecs

"""
Implementation of the teletex T.61 codec. Exports the following items:

 - register()
"""
class TeletexCodec(codecs.Codec):
    def encode(self, input_, errors=...): # -> tuple[bytes, int]:
        ...
    
    def decode(self, input_, errors=...): # -> tuple[str, int]:
        ...
    


class TeletexIncrementalEncoder(codecs.IncrementalEncoder):
    def encode(self, input_, final=...): # -> bytes:
        ...
    


class TeletexIncrementalDecoder(codecs.IncrementalDecoder):
    def decode(self, input_, final=...): # -> str:
        ...
    


class TeletexStreamWriter(TeletexCodec, codecs.StreamWriter):
    ...


class TeletexStreamReader(TeletexCodec, codecs.StreamReader):
    ...


def teletex_search_function(name): # -> CodecInfo | None:
    """
    Search function for teletex codec that is passed to codecs.register()
    """
    ...

def register(): # -> None:
    """
    Registers the teletex codec
    """
    ...

DECODING_TABLE = ...
ENCODING_TABLE = codecs.charmap_build(DECODING_TABLE)
