"""
This type stub file was generated by pyright.
"""

import sys

if sys.version_info < (3, ):
    ...
else:
    str_cls = str
    byte_cls = bytes
    int_types = int
    bytes_to_list = list
    def chr_cls(num): # -> bytes:
        ...
    
def type_name(value): # -> str:
    """
    Returns a user-readable name for the type of an object

    :param value:
        A value to get the type name of

    :return:
        A unicode string of the object's type name
    """
    ...

